### ISSUE TITLE
Question: Can it run well on an embedded platform?

### ISSUE THREAD

**Issue by kokroo** [ringsaturn/tzf-rs#142]
Hi,

Thanks for this useful library, this is exactly what I needed!
I am trying to get the time from a GPS module, and then lat/long as well, and then using both of them to show the user the time in their local timezone.

I am just wondering if this algorithm will be suitable to run on an ESP32 or NRF chip with their limited processing power and RAM?

**Comment by ringsaturn** [comment]
The algorithm and data structure behind this project is designed for server side for high QPS pressure. For generral case, this program need at least 40MB memory to run.

If you need to run under low memory environment, I suggest you read below links:

- https://github.com/HarryVienna/ESP32-Timezone-Finder-Component
	- This project is built for ESP32
- https://github.com/BertoldVdb/ZoneDetect
	- Issue: https://github.com/BertoldVdb/ZoneDetect
- https://github.com/huonw/tz-search
	- This project use an outdated dataset
